services:
  customer:
      container_name: customer
      build:
          dockerfile: Dockerfile
      image: customers:latest
      environment:
        - SPRING_DATASOURCE_URL=jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      ports:
          - 8080:8080
      networks:
          - pfcti-network
  postgres:
      image: postgres:16.3-alpine
      ports:
        - ${POSTGRES_PORT}:5432
      volumes:
        - ~/apps/postgres:/var/lib/postgresql@16/data
        - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      environment:
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_DB=${POSTGRES_DB}
      networks:
          - pfcti-network
networks:
    pfcti-network:
        driver: bridge