@base_url = http://localhost:8080/api
@uri = /customers

### Add Customer
POST {{base_url}}{{uri}}
Content-Type: application/json

{
    "id": "12",
    "firstName": "Alejandro",
    "lastName": "Navarro",
    "phone": "+50683838383",
    "birthDate": "1989-04-18"
}

### Edit Customer
PUT {{base_url}}{{uri}}
Content-Type: application/json

{
    "id": "10",
    "firstName": "Alejandro",
    "lastName": "Navarro Sanchez",
    "phone": "+50683838383",
    "birthDate": "1989-04-18"
}

### Delete Customer
DELETE {{base_url}}{{uri}}/11

### Get Customer By Id
GET {{base_url}}{{uri}}/12

### Get Customers order by birth date desc
GET  {{base_url}}{{uri}}/birthDate

### Get Customers order by id
GET  {{base_url}}{{uri}}/id

### Get Customers order by name
GET  {{base_url}}{{uri}}/birthDate