### Customer Test
GET  http://localhost:8080/customer/test

### Add Customer
POST http://localhost:8080/customer
Content-Type: application/json

{
    "id": "11",
    "firstName": "Alejandro",
    "lastName": "Navarro",
    "phone": "+50683838383",
    "birthDate": "1989-04-18"
}

### Edit Customer
PUT http://localhost:8080/customer
Content-Type: application/json

{
    "id": "10",
    "firstName": "Alejandro",
    "lastName": "Navarro Sanchez",
    "phone": "+50683838383",
    "birthDate": "1989-04-18"
}

### Delete Customer
DELETE http://localhost:8080/customer/8

### Get Customers order by birth date desc
GET  http://localhost:8080/customer/birthDate

### Get Customers order by id
GET  http://localhost:8080/customer/id

### Get Customers order by name
GET  http://localhost:8080/customer/birthDate